apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: asia.gcr.io/poc-innovation-iot/dew-hw3-go-user
  newTag: 103eda26
- name: asia.gcr.io/poc-innovation-iot/dew-hw3-user
  newTag: 8a2fe68a


configMapGenerator:
- behavior: merge
  files:
  - configs/config.yaml
  name: dew-hw3-go-user-configmap-file

secretGenerator:
- behavior: merge
  envs:
  - secrets/secret.env
  name: dew-hw3-go-user-secret-env
