apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/deployment.yaml
  - resources/service.yaml

configMapGenerator:

  # can be other file type
  - name: dew-hw3-go-user-configmap-file
    files:
    - configs/config.yaml

secretGenerator:
  - name: dew-hw3-go-user-secret-env
    envs:
    - secrets/secret.env