apiVersion: apps/v1
kind: Deployment
metadata:
  name: dew-hw3-go-user
  labels:
    app.kubernetes.io/name: dew-hw3-go-user
    app.kubernetes.io/instance: dew-hw3-go-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dew-hw3-go-user
      app.kubernetes.io/instance: dew-hw3-go-user
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dew-hw3-go-user
        app.kubernetes.io/instance: dew-hw3-go-user
    spec:
      containers:
        - name: dew-hw3-go-user
          image: asia.gcr.io/poc-innovation-iot/dew-hw3-go-user:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: dew-hw3-go-user-secret-env
          volumeMounts:
              - mountPath: /config/config.yaml
                name: dew-hw3-go-user-configmap-file
                subPath: config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 64m
              memory: 64Mi
            requests:
              cpu: 32m
              memory: 32Mi
      volumes:
        - name: dew-hw3-go-user-secret-file
          secret:
            secretName: dew-hw3-go-user-secret-file
        - name: dew-hw3-go-user-configmap-file
          configMap:
            name: dew-hw3-go-user-configmap-file